---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: elasticachelogetler-conf
# data:
#   config.yaml: |
#     aws:
#       AWS_ACCESS_KEY_ID: ""
#       AWS_SECRET_ACCESS_KEY: ""
#       AWS_REGION: ""
#     redis:
#       slowlog_num: 128
#     es:
#       address: "http://IP:PORT"
#       index: "redis-slowlog" # 索引
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticachelogetler-cron-prod
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticachelogetler-cron-prod
            image: images_tag
            # args:
            # - /bin/sh
            # - -c
            # - date; echo Hello from the Kubernetes cluster
            volumeMounts:
              - name: elasticachelogetler-conf-prod
                mountPath: /opt/data1/.config.yaml
                subPath: .config.yaml
          restartPolicy: OnFailure
          volumes:
            # - name: elasticachelogetler-cron-log-prod
            #   hostPath:
            #     path: /opt/data1/logs/elasticachelogetler-cron/prod/
          - name: elasticachelogetler-conf-prod
            configMap:
              name: elasticachelogetler-conf
              items:
                - key: config.yaml
                  path: .config.yaml
        