---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: elasticachelogetler-conf
# data:
#   config.yaml: |
#     aws:
#       AWS_ACCESS_KEY_ID: ""
#       AWS_SECRET_ACCESS_KEY: ""
#       AWS_REGION: ""
#     redis:
#       slowlog_num: 128
#     es:
#       address: "http://IP:PORT"
#       index: "redis-slowlog" # 索引
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticachelogetler-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticachelogetler-cron
            image: images_tag
            # args:
            # - /bin/sh
            # - -c
            # - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure